### ISSUE TITLE
shopify app 使用 Github Actions

### ISSUE THREAD

**Issue by huangcong12** [huangcong12/huangcong12.github.io#26]
感谢 Github Actions，这是一个伟大的产品
# 项目部署到 fly.io
参考官方文档：https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
```yml
name: Fly Deploy
on:
    push:
    branches:
        - main # change to main if needed    
jobs:
    deploy:
name: Deploy app
runs-on: ubuntu-latest
concurrency: deploy-group # optional: ensure only one action runs at a time
steps:
- uses: actions/checkout@v3
- uses: superfly/flyctl-actions/setup-flyctl@master
- run: flyctl deploy --remote-only
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

# 主题扩展发布
参考官方文档：https://shopify.dev/docs/apps/tools/cli/ci-cd#github-actions 。但是官方文档里面少了安装 ruby 脚本的部分，下面的脚本代码是补上 ruby 的。
```
name: Deploy app
on:
  push:
    branches:
      - deploy-extensions
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # specify the Ruby version you need
      # Removed "Install Bundler" step because it's already handled by ruby/setup-ruby
      - name: Deploy
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        run: npm run deploy -- -f --source-control-url "$COMMIT_URL"
```

# 补充
记得把 package-lock.json 文件增加到版本控制，要不然 npm install 安装了和开发环境不同的版本扩展，线上会出现意想不到的问题
